sudo: required
services:
  - docker
before_install:
  - docker build -t dvontrec/api-test -f ./api/Dockerfile.dev ./api
script:
  # Should add api tests
  - docker run dvontrec/api-test ls
after_success:
  - docker build -t dvontrec/sprinkle-of-api ./api
  - docker build -t dvontrec/sprinkle-of-nginx ./nginx
  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  Takes images and push to docker hub
  - docker push dvontrec/sprinkle-of-api
  - docker push dvontrec/sprinkle-of-nginx
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: Sprinkle Of Jeezy
  env: SprinkleOfJeezy-env
  bucket_name: elasticbeanstalk-us-east-1-092753704309
  bucket_path: sprinkle-of-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_ACCESS_KEY:
    secure: $AWS_SECRET_KEY
